#!/usr/bin/env python3
"""Generate Adafruit-GFX-format bitmap fonts from a TTF.

Used to produce firmware/src/tiny_fonts.h from DejaVu Sans (Bitstream
Vera license -- permits embedding and derived bitmap fonts with
attribution; see https://dejavu-fonts.github.io/License.html). The
generated header is checked in so neither CI nor the Arduino IDE needs
PIL or the TTFs -- rerun this only to change sizes or faces:

    python3 tools/genfont.py > firmware/src/tiny_fonts.h

Format notes (mirrors Adafruit_GFX / Arduino_GFX gfxfont.h):
- glyph bitmaps are 1-bit, MSB-first, packed CONTINUOUSLY across rows
  (no per-row byte alignment)
- glyph yOffset is relative to the BASELINE (negative = above it)
- the glyph table must cover a contiguous char range [first..last];
  we emit 32..176 so the degree sign (0xB0) rides along, with zero-size
  glyphs filling the unused 127..175 gap.
"""
from PIL import Image, ImageDraw, ImageFont

DEJAVU = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
DEJAVU_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

FIRST, LAST = 32, 176  # ASCII printable + latin-1 gap + degree sign
DEGREE = 176

FONTS = [
    # (c identifier, ttf path, pixel size, charset)
    # charset None = full printable ASCII + degree sign; a string limits
    # the face to just those characters (others become zero-size glyphs)
    # -- used to keep huge display faces from bloating the header.
    ("tiny_sans_18",       DEJAVU,      18,  None),
    # Compact-mode companions (firmware 1.30): the 1.3" compact aspect
    # box scales every coordinate by 200/240; these faces are the same
    # scale applied to the type, so compact mode renders a faithful
    # miniature instead of full-size text overflowing shrunken bounds.
    ("tiny_sans_15",       DEJAVU,      15,  None),
    ("tiny_sans_bold_17",  DEJAVU_BOLD, 17,  None),
    ("tiny_sans_bold_27",  DEJAVU_BOLD, 27,  None),
    ("tiny_sans_bold_30",  DEJAVU_BOLD, 30,  None),
    ("tiny_sans_bold_53",  DEJAVU_BOLD, 53,  None),
    ("tiny_sans_bold_107", DEJAVU_BOLD, 107, "0123456789-. \xb0"),
    ("tiny_sans_bold_20",  DEJAVU_BOLD, 20,  None),
    ("tiny_sans_bold_24",  DEJAVU_BOLD, 24,  None),
    ("tiny_sans_bold_32",  DEJAVU_BOLD, 32,  None),
    ("tiny_sans_bold_36",  DEJAVU_BOLD, 36,  None),
    ("tiny_sans_bold_64",  DEJAVU_BOLD, 64,  None),
    # Digits-only jumbo face for the mist layout's big temperature
    ("tiny_sans_bold_128", DEJAVU_BOLD, 128, "0123456789-. \xb0"),
]


def build_font(name, path, px, charset=None):
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    bitmap = bytearray()
    bitpos = 0

    def push_bit(b):
        nonlocal bitpos
        if bitpos % 8 == 0:
            bitmap.append(0)
        if b:
            bitmap[-1] |= 0x80 >> (bitpos % 8)
        bitpos += 1

    glyphs = []
    for code in range(FIRST, LAST + 1):
        renderable = (32 <= code <= 126) or code == DEGREE
        if charset is not None:
            renderable = renderable and chr(code if code != DEGREE else 0xB0) in charset
        ch = chr(code)
        if not renderable:
            glyphs.append((len(bitmap), 0, 0, 0, 0, 0, code))
            continue
        adv = max(1, round(font.getlength(ch)))
        img = Image.new("L", (adv + px, ascent + descent + 4), 0)
        ImageDraw.Draw(img).text((2, 0), ch, fill=255, font=font)
        bw = img.point(lambda p: 255 if p >= 128 else 0)
        box = bw.getbbox()
        if box is None:  # space etc.
            glyphs.append((len(bitmap), 0, 0, adv, 0, 0, code))
            continue
        x0, y0, x1, y1 = box
        gw, gh = x1 - x0, y1 - y0
        offset = len(bitmap)
        bitpos = 0
        px_data = bw.crop(box).load()
        for yy in range(gh):
            for xx in range(gw):
                push_bit(px_data[xx, yy])
        glyphs.append((offset, gw, gh, adv, x0 - 2, y0 - ascent, code))

    y_advance = ascent + descent + 2
    return bitmap, glyphs, y_advance


def emit(name, bitmap, glyphs, y_advance):
    out = []
    out.append(f"const uint8_t {name}_Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmap), 16):
        row = ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16])
        out.append(f"  {row},")
    out.append("};")
    out.append("")
    out.append(f"const GFXglyph {name}_Glyphs[] PROGMEM = {{")
    for (off, w, h, adv, xo, yo, code) in glyphs:
        label = chr(code) if 33 <= code <= 126 else f"0x{code:02X}"
        out.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, "
                   f"{yo:5d} }},  // '{label}'")
    out.append("};")
    out.append("")
    out.append(f"const GFXfont {name} PROGMEM = {{")
    out.append(f"  (uint8_t *){name}_Bitmaps,")
    out.append(f"  (GFXglyph *){name}_Glyphs,")
    out.append(f"  {FIRST}, {LAST}, {y_advance}")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main():
    print("// Generated by tools/genfont.py -- DO NOT EDIT BY HAND.")
    print("// Bitmap fonts derived from DejaVu Sans (Bitstream Vera license,")
    print("// https://dejavu-fonts.github.io/License.html). The license permits")
    print("// embedding and derived works; DejaVu is credited in About.")
    print("//")
    print("// Include AFTER Arduino_GFX_Library.h (device) or the host stubs --")
    print("// both provide the GFXglyph/GFXfont structs and PROGMEM.")
    print("#pragma once")
    print()
    total = 0
    for name, path, px, charset in FONTS:
        bitmap, glyphs, ya = build_font(name, path, px, charset)
        total += len(bitmap) + len(glyphs) * 7
        print(f"// --- {name}: {px}px, {len(bitmap)} bitmap bytes ---")
        print(emit(name, bitmap, glyphs, ya))
    print(f"// total font data: ~{total // 1024 + 1} KB")


if __name__ == "__main__":
    main()
